### ISSUE TITLE
repo path to puppet5 changed

### ISSUE THREAD

**Issue by logicminds** [example42/puppet-psick#37]
https://github.com/example42/puppet-psick/blob/master/tasks/puppet_install.sh#L76

For puppet 5 this is now like:

https://apt.puppetlabs.com/puppet5-release-xenial.deb

**Comment by tuxmea** [comment]
@logicminds can you provide a PR?

**Comment by alvagante** [comment]
We already adapted the install_puppet script on the psick control-repo to install puppet 5:
https://github.com/example42/psick/blob/production/bin/puppet_install.sh

And have a new one for Puppet 4 (which was the same of the older puppet_install.sh):
https://github.com/example42/psick/blob/production/bin/puppet_install4.sh

Since the task here is heavily based on that script, we can simply import and adapt them here, eventually adding a puppet_install4 task
